# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8282ee67b5ad14de7a422414db535cb841b63ff9e143e80fe05bda0ed0ffe9b01ab6f36c472a7cda557ee87cec8dbbb847fee17f670ee39a2e6fad5bb8f53afe

test:
  secret_key_base: 66ac7c73c6c48af717a74de5ca5fc74fa71530a42f08499cd4d8e7b10c72a290dd27d109e56bccbbe492f65e61e64d600258e57d80750f3f09a6fca102b77f49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
